### ISSUE TITLE
ECONNRESET Error When Trying to Post to Threads

### ISSUE THREAD

**Issue by a-burlakovv** [junhoyeo/threads-api#101]
I've been trying to use the threads-api library to post to my Threads account programmatically. However, I'm encountering an ECONNRESET error and I'm unsure how to proceed.

Here's the script I'm using:

import { ThreadsAPI } from 'threads-api';

const main = async () => {
  const threadsAPI = new ThreadsAPI({
    username: 'my_username', // My actual username is replaced here
    password: 'my_password', // My actual password is replaced here
  });

  await threadsAPI.publish({
    text: '🤖 Hello World',
  });
};

main();

When I run this script, I get the following error:

AxiosError: read ECONNRESET
...

The error suggests that the other side of the TCP conversation (in this case, the Instagram server) is unexpectedly closing the connection. I'm not sure why this is happening. My internet connection seems to be stable, and I've verified that my username and password are correct.

Could you provide any guidance on what might be causing this issue and how I could resolve it? Any help would be greatly appreciated.

**Comment by a-burlakovv** [comment]
I figured this one on my own – i am from Russia and Instagram is blicking nay traffic from my country. So i used VPN instead and everything worked.

**Comment by junhoyeo** [comment]
@a-burlakovv Thanks for the follow-up! 🙏 Too bad to hear Instagram blocking Russia 😭
