### ISSUE TITLE
Issue in Fetching UserId from Username

### ISSUE THREAD

**Issue by Shaivpidadi** [junhoyeo/threads-api#108]
I am currently using threadsAPI.getUserIDfromUsername to get userId but it works only sometime, rest of the time it returns undefined. Is there any alternative function to be used? or any alternative approach which make sure it works all the time.

**Comment by cedriking** [comment]
Seems this is solved in https://github.com/junhoyeo/threads-api/pull/106 . Updated version should be out soon.

**Comment by junhoyeo** [comment]
Can you check again after updating to latest version?
