### ISSUE TITLE
Beginner issue

### ISSUE THREAD

**Issue by gateof15th** [junhoyeo/threads-api#114]
Sorry, I'm a beginner. What are the steps to run this API?

**Comment by AayushGithub** [comment]
This a Node.js/TypeScript client for Meta's Threads that supports read and write operations. 

# Installation
Before anything else, you need to install the library. As it's a Node.js library, you can install it using npm:

`npm install threads-api`

Make sure you have Node/Deno installed 

https://nodejs.org/en/download
https://deno.land/

After this I would highly recommend checking out [this section](https://github.com/junhoyeo/threads-api/blob/main/threads-api/README.md#-usage-read) for some example code.
