### ISSUE TITLE
I cannot login 

### ISSUE THREAD

**Issue by vietduc030496** [junhoyeo/threads-api#122]
when login, i reiceve response below:
{"message":"Payload returned is null. A server error field_exception occured. Check server logs for details.","status":"fail"}

**Comment by junhoyeo** [comment]
@vietduc030496 yo, I think this can be related to #125 which have been fixed in  [v1.4.0](https://github.com/junhoyeo/threads-api/releases/tag/v1.4.0) right now. Can you try it out after updating to the latest version? 🚀
