### ISSUE TITLE
Add option `maxRetries` to `ThreadsAPI`, Implement login retries up to `maxRetries` on an exponential backoff

### ISSUE THREAD

**Issue by junhoyeo** [junhoyeo/threads-api#129]

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues(like adding expo backoff) by writing pull requests. 
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try.
We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)

**Comment by junhoyeo** [comment]
Shipped in [v1.4.1](https://github.com/junhoyeo/threads-api/releases/tag/v1.4.1).
thanks to @cedriking, cc @SethuSenthil
@wwzeng1 Thanks for the intro! I'll promise to try out Sweep on some other issue 🔨  (Excited to collab!)

**Comment by wwzeng1** [comment]
Great to hear! Don't hesitate to reach out, my email is william@sweep.dev, we also have discord https://discord.com/invite/sweep-ai
