### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by AnthonyASanchez** [junhoyeo/threads-api#139]
console.error
      [LOGIN] Failed to login TypeError: Cannot read properties of undefined (reading 'split')

**Comment by AnthonyASanchez** [comment]
This Is within the credentials test

**Comment by sidgithub780** [comment]
@AnthonyASanchez I get the same error when trying to post to threads from an AWS lambda function

<img width="786" alt="Screenshot 2023-07-12 at 9 55 04 PM" src="https://github.com/junhoyeo/threads-api/assets/53668449/a9351d89-50d3-4752-8099-ed7287b4fc1e">

**Comment by c4ei** [comment]
.env 
USERNAME  --> USER_NAME 
all same 6 file 
process.env.USERNAME  --> process.env.USER_NAME


change try !!!!

**Comment by AnthonyASanchez** [comment]
@c4ei how would this fix it?

**Comment by AnthonyASanchez** [comment]
The retry fixed the issue, looks like it just needs to make multiple requests sometimes
