### ISSUE TITLE
How to `add` when creating a thread? (Fetching `PostID` Impossible)

### ISSUE THREAD

**Issue by cedriking** [junhoyeo/threads-api#149]
Hi everyone, amazing work and progress on the threads-api.
I was wondering how can we post multiple threads one under the other? I was thinking it would be as simple as getting the post ID of the last published thread and keep going that way, but as soon as the first thread is published, I get this error:
```
data: { message: 'Unknown Server Error.', status: 'fail' }
```
I even tried to pause for 10 secs and it's still not working 🤔 

The code I was trying is simple:
```js
let parentPostID
for (const thread of data) {
  parentPostID = await threadsAPI.publish({
    text: thread.text,
    image: thread.image,
    parentPostID,
  })
  await sleep(10000)

  console.log(`Posted thread ${parentPostID}`)
}
```

Thanks for your help.

**Comment by cedriking** [comment]
I tried that already. After the sleep of 10secs I had
```js
await threadsAPI.getUserProfileThreads(userID)
```
But it always return an empty array `[]` even that I have many posts created.

Also tried the following in case the returned string from `publish()` is a threadID and not a postID, but that returns undefined:
```js
parentPostID = await threadsAPI.getPostIDfromThreadID(parentPostID)
```

So far the only thing that returns something that makes sense is `publish()` but that doesn't work when trying to be used as the `parentPostID`.

**Comment by junhoyeo** [comment]
[<img width="601" alt="image" src="https://github.com/junhoyeo/threads-api/assets/32605822/a9e48d1f-7cc0-484c-9169-4aa844fc3e6f">](https://www.threads.net/t/CuqbBI8h19H)
https://www.threads.net/t/CuqbBI8h19H

Looks like the webpage that `getPostIDfromThreadID`(`getPostIDfromThreadURL`) uses to fetch `postID` is dead 🤔

**Comment by junhoyeo** [comment]
Update: Think implementing https://github.com/junhoyeo/threads-py/pull/27 here too could be a fix.

**Comment by cedriking** [comment]
Seems it's back @junhoyeo 🙌🏼 I'm not able to post (not even single ones) now though 😰

**Comment by cedriking** [comment]
Thank you so much @junhoyeo for fixing this one. Waiting for the patch release 🙌🏼

**Comment by junhoyeo** [comment]
Sorry I was late, just deployed https://github.com/junhoyeo/threads-api/releases/tag/v1.4.4!

**Comment by aleclarson** [comment]
I'm also getting `Unknown Server Error` when trying to post a reply to a post I just created (tested with v1.4.4).

**Comment by cedriking** [comment]
Same here, seems the issue is still active:
```
data: { message: 'Unknown Server Error.', status: 'fail' }
```
