### ISSUE TITLE
Can't publish anymore

### ISSUE THREAD

**Issue by yssf-io** [junhoyeo/threads-api#161]
It looks like Threads blocked usage (except for the timeline) to people in Europe; and it has the same effect on the API unfortunately.

I'm not sure what the criteria are, because out of 3 accounts, mine and two bots, only 2 of them (mine and one bot) don't work, even though the bots are on the same server somewhere in Paris.

So I think the block (if it's a block and not just an outage) is more complex than geolocation.

**Comment by kevinfosse** [comment]
My Thread application no longer works, I can't retrieve anything from my feed etc...

I've tried running the api on a VPS server hosted in the USA and that doesn't work either, so I assume it's Threads itself, 

However, one strange thing, when recreating an instagram account from its browser, the Thread app works for the new account. 

If it helps, here are the logs I get from my US-based VPS

`(node:29517) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 429
    at settle (/root/test/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/root/test/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)`

**Comment by yssf-io** [comment]
I don't think there's anything we can do for now except wait for Threads to be available again for Europeans.

Going to be difficult for me to contribute to the project again until then @junhoyeo, but I'll keep following it :)
