### ISSUE TITLE
"WARNING:  deviceID not provided" log

### ISSUE THREAD

**Issue by Aerglonus** [junhoyeo/threads-api#167]
After new release the #151 resolved this issue with .env variables to prevent login issues. 

Warning log showing even when .env or option.deviceID is passed to the constructor.

`WARNING: deviceID not provided, automatically generating device id 'android-".env THREADS_DEVICE_ID value" Please save this device id and use it for future uses to prevent login issues. You can provide this device id by passing it to the constructor or setting the THREADS_DEVICE_ID environment variable (.env file)`

On [commit for #151 ](https://github.com/junhoyeo/threads-api/pull/151/files#diff-a0ae255b36f5cb107ebf68b94c00973a564b5dd5450e3c041cf8b44ecd0233b0R176-R178) this was added
```diff
 + if (options?.deviceID ?? process.env.THREADS_DEVICE_ID) {
      console.warn(
        `⚠️ WARNING: deviceID not provided, automatically generating device id '${this.deviceID}'`,
     )
  ```
  
  Shouldn't this only be triggered if no value is present on .env or constructor  like this ? 
  
  ```diff
   + if (!options?.deviceID ?? !process.env.THREADS_DEVICE_ID) {
      console.warn(
        `⚠️ WARNING: deviceID not provided, automatically generating device id '${this.deviceID}'`,
     )
 ```

**Comment by junhoyeo** [comment]
@Aerglonus code was written a bit complicated, so I cleaned it up entirely in #168 🚀

**Comment by junhoyeo** [comment]
@Aerglonus Sorry I was late, just deployed https://github.com/junhoyeo/threads-api/releases/tag/v1.4.4!

**Comment by heroaltman** [comment]
Is there any way to save or return the Device ID that threads-api generates

**Comment by Aerglonus** [comment]
> Is there any way to save or return the Device ID that threads-api generates

If you didn't pass a device-id it should output the generated one with the warning message  in your console. Then you can use pass that.

**Recommended:**  If you happen to have an android phone you can get its deviceID and pass it along with the device indentifiers(os_release, android version, etc)
