### ISSUE TITLE
module error 

### ISSUE THREAD

**Issue by nastarrr** [junhoyeo/threads-api#172]
Error: Cannot find module 'dotenv/config'
Require stack:
- /node_modules/threads-api/build/threads-api.js
- /node_modules/threads-api/build/index.js

**Comment by MsLolita** [comment]
npm install dotenv

import 'dotenv/config';
import './index.js';

**Comment by junhoyeo** [comment]
Hey @nastarrr! Just deployed https://github.com/junhoyeo/threads-api/releases/tag/v1.4.5, which has this issue fixed. Can you update to the latest version?  🚀 
Installing `dotenv` to your project manually, like in @MsLolita's solution, will work for previous versions. 👍
