### ISSUE TITLE
Error: User ID not found

### ISSUE THREAD

**Issue by kostyaavdonin** [junhoyeo/threads-api#209]
I want to log in and send a post as shown in example...

I did it, the post went. but when I re-authorize and send the post, I get: Error: User ID not found

code:

 const threadsAPI = new ThreadsAPI({
        username: context.scene.state.login,
        password: context.scene.state.password,
        deviceID: `android-${(Math.random() * 1e24).toString(36)}`,
 });

let post = await threadsAPI.publish({
        text: '🤖 Hello World!',
 });
 
 console.log(threadsAPI) -->
 
 {
  verbose: false,
  token: undefined,
  fbLSDToken: ,
  noUpdateToken: false,
  noUpdateLSD: false,
  device: undefined,
  userID: undefined,
  locale: 'en-US',
  maxRetries: 1,
  syncLoginExperiments: [Function (anonymous)],
  encryptPassword: [Function (anonymous)],
  login: [Function (anonymous)],
  _getAppHeaders: [Function (anonymous)],
  _getInstaHeaders: [Function (anonymous)],
  _getDefaultHeaders: [Function (anonymous)],
  getProfilePage: [Function (anonymous)],
  getUserIDfromUsernameWithInstagram: [Function (anonymous)],
  getUserIDfromUsername: [Function (anonymous)],
  getCurrentUserID: [Function (anonymous)],
  _requestQuery: [Function (anonymous)],
  _destructureFromUserIDQuerier: [Function (anonymous)],
  getUserProfile: [Function (anonymous)],
  getUserProfileThreads: [Function (anonymous)],
  getUserProfileThreadsLoggedIn: [Function (anonymous)],
  getUserProfileReplies: [Function (anonymous)],
  getUserProfileRepliesLoggedIn: [Function (anonymous)],
  getUserFollowers: [Function (anonymous)],
  getUserFollowings: [Function (anonymous)],
  getPostIDfromThreadID: [Function (anonymous)],
  getPostIDfromURL: [Function (anonymous)],
  getThreads: [Function (anonymous)],
  getThreadLikers: [Function (anonymous)],
  getTimeline: [Function (anonymous)],
  _toggleAuthPostRequest: [Function (anonymous)],
  like: [Function (anonymous)],
  unlike: [Function (anonymous)],
  follow: [Function (anonymous)],
  unfollow: [Function (anonymous)],
  repost: [Function (anonymous)],
  unrepost: [Function (anonymous)],
  getToken: [Function (anonymous)],
  _lastUploadID: 0,
  _nextUploadID: [Function (anonymous)],
  _createUploadMetadata: [Function (anonymous)],
  publish: [Function (anonymous)],
  delete: [Function (anonymous)],
  publishWithImage: [Function (anonymous)],
  uploadImage: [Function (anonymous)],
  httpAgent: undefined,
  httpsAgent: undefined,
  username: 
  password:
  deviceID: 'android-1vys7sou010g0000'
}

**Comment by kostyaavdonin** [comment]
@junhoyeo how to fix it?

**Comment by kostyaavdonin** [comment]
When calling a function getUserIdfromusername I get an answer:  statusText: 'Too Many Requests',

**Comment by junhoyeo** [comment]
> @junhoyeo how to fix it?

Set `verbose`. Let's see what happens under the hood. It may occurred cuz of rate limits.

**Comment by kostyaavdonin** [comment]
> > @junhoyeo how to fix it?
> 
> Set `verbose`. Let's see what happens under the hood. It may occurred cuz of rate limits.

                const threadsAPI = new ThreadsAPI({
                    username: context.scene.state.login,
                    password: context.scene.state.password,
                    deviceID: `android-${(Math.random() * 1e24).toString(36)}`,
                    verbose: true
                });
                
               Like this?

**Comment by junhoyeo** [comment]
> Like this?

Yes!

**Comment by kostyaavdonin** [comment]
> > @junhoyeo how to fix it?
> 
> Set `verbose`. Let's see what happens under the hood. It may occurred cuz of rate limits.

[userID] UPDATED undefined
Error: User ID not found
    at o.<anonymous> (/home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:20472)
    at /home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:2620
    at Object.next (/home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:2725)
    at i (/home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:481)
    at o (/home/superman_da/threads-cheating/node_modules/threads-api/build/threads-api.js:1:678)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by kostyaavdonin** [comment]
> > Like this?
> 
> Yes!

I also got a lot of text... here's the bottom part, I don't have to be able to copy everything.
                                                                                                                                     \":{\"㐸\":{\")\":1}}}}],\"
    \":{\"㐸\":{\"6\":\"100%\",\"=\":\"6dp\",\"7\":\"6dp\",\")\":1,\"A\":1,\";\":\"6dp\",\"8\":\"6dp\"}}}}],\"
                                                                                                              \":{\"㐸\":{\"2\":\"-6dp\",\",\":\"-6dp\",\")\":1,\"1\":\"-6dp\",\"-\":\"-6dp\"}}}}],\"
\":[],\"
        \":{\"㐸\":{\"D\":\"100%\",\"9\":\"10dp\",\":\":\"10dp\",\"7\":\"10dp\",\")\":1,\"#\":\"center\"}}}}],\"
                                                                                                                \":{\"㐸\":{\"=\":\"16dp\",\"9\":\"16dp\",\":\":\"16dp\",\"7\":\"16dp\",\")\":1}}}}],\"
                                           \":{\"㐸\":{\"A\":0}}}}],\"
\":[{\"㙚\":{\")\":\" (bk.action.core.TakeLast, (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \"login_type\"), (bk.action.array.Make, \"Password\"))), (bk.action.qpl.MarkerEndV2, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.i32.Const, 2), (bk.action.tree.Make, (bk.action.i32.Const, 13704))))\"}}],\"
                                                                                                   \":{\"㐸\":{\"D\":\"100%\",\"*\":\"100%\"}}}}],\"
                                                                                                                                                    \":{\"㐸\":{\"D\":\"100%\"}}}}}}}}],\"props\":[{\"id\":\"-6917714003244327204\",\"name\":\"ttrc_instance_id\"},{\"id\":\"2231046902902521263\",\"name\":\"override_login_success_action\"}],\"error_attribution\":{\"logging_id\":\"{\"callsite\":\"{\"product\":\"bloks_caa_login\",\"feature\":\"com.bloks.www.bloks.caa.login.async.send_login_request\",\"integration\":\"bloks_screen\",\"oncall\":\"caa_login\"}\",\"push_phase\":\"C3\",\"version\":1,\"request_id\":\"AhXVM_4Vuapf7aGB0lwwTq6\"}\"},\"tree\":{\"㐟\":{\"#\":\" (bk.action.core.TakeLast, (bk.action.i32.Const, 1), (bk.action.qpl.MarkerAnnotate, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), (bk.action.map.Make, (bk.action.array.Make, \"login_type\", \"login_source\"), (bk.action.array.Make, \"Password\", \"Login\"))), (bk.action.qpl.MarkerPoint, (bk.action.i32.Const, 2293785), (bk.action.i32.Const, 0), \"success_response\", (bk.action.tree.Make, (bk.action.i32.Const, 13747))), (bk.action.i32.Const, 1), (bk.action.i32.Const, 1), (bk.action.core.Match, (bk.action.caa.GetSPIEligibility, \"39074239527\"), (bk.action.array.Make, (bk.action.core.Pattern, (bk.action.bool.Const, true), (bk.action.core.FuncConst, (bk.action.fx.PushSyncScreen, (bk.action.tree.Make, (bk.action.i32.Const, 16237), (bk.action.i32.Const, 35), \" (bk.action.map.Make, (bk.action.array.Make, \"app_id\"), (bk.action.array.Make, \"com.bloks.www.caa.login.save-credentials\"))\", (bk.action.i32.Const, 40), (bk.action.i32.Const, 719983200), (bk.action.i32.Const, 38), \"o7f2v0:2\", (bk.action.i32.Const, 41), \"com.bloks.www.caa.login.save-credentials\"), (bk.action.bloks.ParseHoistedPayload, \"146364908400004\"), (bk.action.tree.Make, (bk.action.i32.Const, 16087)))))), (bk.action.core.Default, (bk.action.core.FuncConst, (bk.action.caa.HandleLoginResponse, (bk.action.tree.Make, (bk.action.i32.Const, 15942), (bk.action.i32.Const, 35), \"{\"login_response\":\"{\"logged_in_user\":{\"has_anonymous_profile_picture\":false,\"supervision_info\":{\"is_eligible_for_supervision\":false,\"is_supervised_user\":false,\"is_supervised_or_in_cooldown\":false,\"has_guardian\":false,\"is_guardian_user\":false,\"is_supervised_by_viewer\":false,\"is_guardian_of_viewer\":false,\"has_stated_age\":true,\"screen_time_daily_limit_seconds\":null,\"screen_time_daily_limit_description\":null,\"fc_url\":\"https://familycenter.instagram.com/dashboard/\",\"quiet_time_intervals\":null,\"is_quiet_time_feature_enabled\":false,\"daily_time_limit_without_extensions_seconds\":null,\"latest_valid_time_limit_extension_request\":null},\"is_supervision_features_enabled\":true,\"all_media_count\":602,\"liked_clips_count\":2853,\"page_id\":100933615426521,\"page_name\":\"u0410u043du043eu043du0438u043cu043du044bu0439 u0427u0430u0442 u0422u0435u043bu0435u0433u0440u0430u043c\",\"fbid_v2\":17841439105834279,\"text_post_app_take_a_break_setting\":0,\"interop_messaging_user_fbid\":17845886675303528,\"is_using_unified_inbox_for_direct\":false,\"biz_user_inbox_state\":0,\"show_insights_terms\":false,\"nametag\":{\"mode\":0,\"gradient\":0,\"selfie_sticker\":0,\"emoji\":\"ud83dude00\"},\"allowed_commenter_type\":\"any\",\"has_placed_orders\":false,\"reel_auto_archive\":\"on\",\"total_igtv_videos\":12,\"has_igtv_series\":false,\"can_boost_post\":true,\"can_see_organic_insights\":true,\"wa_addressable\":true,\"wa_eligibility\":0,\"can_hide_category\":true,\"can_hide_public_contacts\":true,\"should_show_category\":true,\"category_id\":2700,\"is_category_tappable\":true,\"should_show_public_contacts\":false,\"is_business\":true,\"professional_conversion_suggested_account_type\":2,\"account_type\":2,\"has_onboarded_to_text_post_app\":true,\"text_post_app_joiner_number\":43144390,\"pk\":39074239527,\"pk_id\":\"39074239527\",\"username\":\"ruanon_bot\",\"full_name\":\"u0410u043du043eu043du0438u043cu043du044bu0439 u0427u0430u0442 | u0417u043du0430u043au043eu043cu0441u0442u0432u0430 | u0414u0435u0432u0443u0448u043au0438\",\"is_private\":false,\"is_verified\":false,\"profile_pic_id\":\"3141144386700752762_39074239527\",\"profile_pic_url\":\"https://scontent-ams4-1.cdninstagram.com/v/t51.2885-19/358004364_239179288919342_5092271778350428464_n.jpg?stp=dst-jpg_s150x150u0026_nc_ht=scontent-ams4-1.cdninstagram.comu0026_nc_cat=102u0026_nc_ohc=imdwYwy1CNcAX_otg_-u0026edm=AAAAAAABAAAAu0026ccb=7-5u0026oh=00_AfBvPuwTm3xfiW82vIelYGVeGH7gRtoKGmZOB0aYmokW9wu0026oe=64BC11FF\",\"is_call_to_action_enabled\":false,\"category\":\"Personal blog\",\"account_badges\":[],\"third_party_downloads_enabled\":0,\"allow_contacts_sync\":false,\"phone_number\":\"+79012861909\",\"country_code\":7,\"national_number\":9012861909},\"session_flush_nonce\":null,\"status\":\"ok\"}\",\"headers\":\"{\"IG-Set-Authorization\": \"Bearer IGT:2:eyJkc191c2VyX2lkIjoiMzkwNzQyMzk1MjciLCJzZXNzaW9uaWQiOiIzOTA3NDIzOTUyNyUzQWVjbkFNbksxQTlXRHNWJTNBMTIlM0FBWWMzVlRxeUhDN0YzLUQyUDRZQ015anhuckl2aWY3ZWFldW1XOHdieGcifQ==\", \"IG-Set-Password-Encryption-Key-Id\": \"158\", \"IG-Set-Password-Encryption-Pub-Key\": \"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1WUdVOUlLdEVpbVNLZTZ4UzRiUwpkSHRLTFkxZU5KVk4yRktzc0NuVThwYWdZN3NWVWJvRHJYcVVyQ2ZEd0JRcmZUYUY2ODBzSjMxS01Md1h4Ykp4Cnd2aU1iRTZpcEdod3FodjlLajJjWGtLcGQ5Y2dqdDFZdzh5bGRhd0NkVDFPRG5SVFlPTUNHT29pVDYrWHl3dmcKZXgyb0h3dEVVMlJ0Y290SnQwVXlwS0lka0dxdGltR0RWdVZscnR3bVVvamhmV0JmbWpQQ2NFZ0VtMXJVQm5VagoxcXI0bUJZQXFiVExYOXhsdXF0a3kwaVM1R0R5cHFSMG9SQ3U0dHl1U0ZXRmFJY0xZUmx1VWQ0Y1pjUWRrSEVpCmN6bWZaWVMwK3RaUGl0R0hUbjc4VExVajlVRTNQSEVJWm5WRGRmZWcvVTk2V3c4SERnWGtJTkJYYTVCRDVJOXMKSlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==\", \"Access-Control-Expose-Headers\": \"X-IG-Set-WWW-Claim\", \"IG-Set-X-MID\": \"ZLbj1wABAAGB6LQF2Rs7K-r2EE7v\", \"X-IG-Reload-Proxy-Request-Info\": \"{\"request_index\": 468, \"view_name\": \"None.None\", \"uuid\": \"6d49a60cf5344c18b53116816ec824de\", \"sanitized_path\": \"/accounts/caa_ig_authentication_thrift_server/\"}\", \"Cross-Origin-Opener-Policy\": \"same-origin-allow-popups;report-to=\"coop\"\", \"x-fb-endpoint\": \"\", \"X-Frame-Options\": \"SAMEORIGIN\", \"Cache-Control\": \"private, no-cache, no-store, must-revalidate\", \"Pragma\": \"no-cache\", \"Expires\": \"Sat, 01 Jan 2000 00:00:00 GMT\", \"Strict-Transport-Security\": \"max-age=31536000\", \"X-Content-Type-Options\": \"nosniff\", \"X-Xss-Protection\": \"0\", \"ig-set-ig-u-ds-user-id\": 39074239527, \"ig-set-ig-u-rur\": \"CLN\", \"Cross-Origin-Embedder-Policy-Report-Only\": \"require-corp;report-to=\"coep\"\"}\",\"cookies\":null}\", (bk.action.i32.Const, 36), \"Password\", (bk.action.i32.Const, 38), \"Login\"), null, (bk.action.core.GetArg, 0))))), null, null, null, null, (bk.action.i32.Const, 1), (bk.action.i32.Const, 1), (bk.action.map.Make, (bk.action.array.Make, \"should_dismiss_loading\"), (bk.action.array.Make, (bk.action.bool.Const, false))))\"}}}},\"status\":\"ok\"}"

**Comment by kostyaavdonin** [comment]
похоже что библиотека не верно извлекла ID

я сейчас вручную вытащил свой айди и вставил в код и все заработало

const threadsAPI = new ThreadsAPI({
                    username: context.scene.state.login,
                    password: context.scene.state.password,
                    deviceID: `android-${(Math.random() * 1e24).toString(36)}`,
                    verbose: true,
                    userID: 39074239527
                });

**Comment by kostyaavdonin** [comment]
@junhoyeo in the new update of the module, please check the receipt of ID.

**Comment by junhoyeo** [comment]
> @junhoyeo Haven’t solved the problem with getting an id yet?

We believe this issue has been fixed in the latest version of [v1.5.3](https://github.com/junhoyeo/threads-api/releases/tag/v1.5.3). Can you try again after updating the package? @kostyaavdonin

**Comment by kostyaavdonin** [comment]
> We believe this issue has been fixed in the latest version of [v1.5.3](https://github.com/junhoyeo/threads-api/releases/tag/v1.5.3).
> Can you try again after updating the package? @kostyaavdonin

Okay. I'll check when I'm free. I'll write to you about the results.

I'll try with resident proxies and regular ones
