### ISSUE TITLE
suspicious login attempt

### ISSUE THREAD

**Issue by dwhieb** [junhoyeo/threads-api#218]
I'm getting a suspicious login notice in the Threads app every time I try to log in using this API. Any tips for how I might avoid this? Thanks!

**Comment by Aerglonus** [comment]
The unidentified login notice is because the automatically generated `deviceID` so pass it but also include  `userID`, `token` and if you have an android that you already logged in with added to the device option

```typescript
  const threadsAPI = new ThreadsAPI({
    verbose: true,
    device: {
      manufacturer: 'Your device manufacturer,
      model: 'Your device model',
      os_version: Your device android version,
      os_release: 'Your device manufacturer OS version',
    },
}

```
