### ISSUE TITLE
Remove unnecessary console.logs

### ISSUE THREAD

**Issue by kostyaavdonin** [junhoyeo/threads-api#232]
When calling a function: getUserProfile()

Comes out:

{

data: { userData: { user: [Object] } },
extensions: { is_final: true }
}

Also the getUserFollowers and getUserFollowings function gives only 100 elements... why?

**Comment by Aerglonus** [comment]
The first one is not a bug it just the console.log here 
https://github.com/junhoyeo/threads-api/blob/74ded4b1bce9f59b1c3b547e353ecc2025a5a0a2/threads-api/src/threads-api.ts#L664-L666

the data is in the variable you are using with the method

```typescript
const userProfile = await threadsAPI.getUserProfile()
// all the data is in userProfile
```

The second one `getUserFollowers` and `getUserFollowings` have pagination so its up to you

```typescript
const { users, next_max_id: cursor } = await threadsAPI.getUserFollowers(userID);
console.log(JSON.stringify(users));
```

**Comment by ttptracker** [comment]
> The first one is not a bug it just the console.log here
> 
> https://github.com/junhoyeo/threads-api/blob/74ded4b1bce9f59b1c3b547e353ecc2025a5a0a2/threads-api/src/threads-api.ts#L664-L666
> 
> the data is in the variable you are using with the method
> 
> ```ts
> const userProfile = await threadsAPI.getUserProfile()
> // all the data is in userProfile
> ```
> 
> The second one `getUserFollowers` and `getUserFollowings` have pagination so its up to you
> 
> ```ts
> const { users, next_max_id: cursor } = await threadsAPI.getUserFollowers(userID);
> console.log(JSON.stringify(users));
> ```

@Aerglous any idea why it doesn't return next_max_id?

https://github.com/junhoyeo/threads-api/issues/231

**Comment by kostyaavdonin** [comment]
> 

Thank you! You helped me a lot.
