### ISSUE TITLE
Enhancement: Working around dotenv related errors while using non-standard bundlers

### ISSUE THREAD

**Issue by suvam0451** [junhoyeo/threads-api#233]
**To Reproduce:**

Try to use the library from client-side javascript, bundled with vite.

**Bug Description:**

Currently building a client-side app and running into issues with vite.

**Expected Behaviour:**

To allow seamless integration with client-side and server-side js, we should document usage and caveat for non-standard use cases.

![Screenshot 2023-07-21 212123](https://github.com/junhoyeo/threads-api/assets/44526763/088c678c-e99a-4fc6-a958-f8e7ad4f4034)

I will continue to figure out workarounds for this issue and post them here (I don't think we should remove dotenv, per se) 👍

**Comment by suvam0451** [comment]
For starters, `process` not being available is a vite issue.

**Workaround** --> https://github.com/vitejs/vite/issues/1973#issuecomment-787571499


**Next Issue Faced:** 

![Screenshot 2023-07-21 212433](https://github.com/junhoyeo/threads-api/assets/44526763/1e5d3892-3cd1-4992-9a94-ffdbc891e24e)

![Screenshot 2023-07-21 212506](https://github.com/junhoyeo/threads-api/assets/44526763/ca86eff3-58f3-4638-a6d8-13b841ea0e8c)

I believe this is because I defined `proces.env` as an (empty) object.

**Comment by junhoyeo** [comment]
@suvam0451 Released your patch in https://github.com/junhoyeo/threads-api/releases/tag/v1.5.4. Thank you very much! 🎉
