### ISSUE TITLE
How do you generate a token?

### ISSUE THREAD

**Issue by agrawalishaan** [junhoyeo/threads-api#236]
Thanks for making this API,

I am trying to generate a token so I can be authenticated, and access private routes using my token + userID, as opposed to a user + pass. How do I generate this token? I saw that we use the `login` function call but I couldn't figure out how to get it working nor find documentation.

**Comment by junhoyeo** [comment]
```tsx
const threadsAPI = new ThreadsAPI({
  username: '_junhoyeo', // Your username
  password: 'PASSWORD', // Your password
});

const token = await threadsAPI.getToken()
console.log(token)
console.log(threadsAPI.token)
```
