### ISSUE TITLE
Are logins cached across code reruns? [question]

### ISSUE THREAD

**Issue by agrawalishaan** [junhoyeo/threads-api#237]
Thanks for this library,

currently, I am logging in and making a post like this:

```ts
const main = async () => {
  const threadsAPI = new ThreadsAPI({
    username: process.env.user,
    password: process.env.pass,
  });

  await threadsAPI.publish({
    text: '🤖 Hello World',
  });
};

main();
```

To my understanding, the way this works is:

1) When I create a threadsAPI object, I pass the user and pass parameters.
2) When I call a route on the instance of my object, for the first time, a token is automatically generated based on the earlier arguments. The sessions is validated and internally stored.
3) Future api route calls to my instance re-use this generated session, as to not log in each time.

Is this correct? So if I call `.publish`, then later `.repost`, the `.repost` call will reuse the session that was initially created?

And are sessions preserved across code-runs, or is the internally cached session deleted, meaning each time I rerun my code, exactly one login attempt is retriggered?

Thanks for anyone who can provide help!

**Comment by junhoyeo** [comment]
> Is this correct? So if I call .publish, then later .repost, the .repost call will reuse the session that was initially created?

Correct :)
