### ISSUE TITLE
Is there a way to get a list of notifications as well as clear them?

### ISSUE THREAD

**Issue by agrawalishaan** [junhoyeo/threads-api#238]
Thanks for making this repo,

I checked all the routes, but couldn't seem to find the route that does this in the title. Is there a route for it? I did see some other APIs have it.

**Comment by junhoyeo** [comment]
Will be added in #189 :)

**Comment by junhoyeo** [comment]
Was introduced in https://github.com/junhoyeo/threads-api/releases/tag/v1.6.2. Use `getNotifications` and `setNotificationsSeen`.

**Comment by agrawalishaan** [comment]
> Was introduced in https://github.com/junhoyeo/threads-api/releases/tag/v1.6.2. Use `getNotifications` and `setNotificationsSeen`.

Thanks you are awesome!
