### ISSUE TITLE
Does anyone who know not opening the shared post url?

### ISSUE THREAD

**Issue by allsoft777** [junhoyeo/threads-api#244]
below is my shared post url.
But, i says an invalid url. So, i couldn't use several apis.
who knows?

https://www.threads.net/t/Cu_Xnw7xwiV/?igshid=NTc4MTIwNjQ2YQ==

**Comment by junhoyeo** [comment]
afaik that's a problem/bug with Threads itself

**Comment by allsoft777** [comment]
Thanks❤️

2023년 7월 23일 (일) 오후 10:23, Junho Yeo ***@***.***>님이 작성:
