### ISSUE TITLE
How are we obtaining the `x-fb-lsd` token?

### ISSUE THREAD

**Issue by nasty-nick-tv** [junhoyeo/threads-api#26]
Hi,

I am copying these calls into a Java client.

How can we obtain the 'x-fb-lsd' token?

Thanks

**Comment by junhoyeo** [comment]
Hi @nasty-nick-tv! We obtain the token by parsing the HTML doc.

This logic is inside both `getUserIDfromUsername` and `getPostIDfromURL`. We use it to update the token each time those methods are called.

https://github.com/junhoyeo/threads-api/blob/c86f4d8506520d677dccc86c64470dc18b02dc54/threads-api/src/threads-api.ts#L194C1-L203C1

Best of luck with your client! I would greatly appreciate it if you could reference my work here (Rest assured, I'll do the same for you in this project's `README.md`).

**Comment by Digital39999** [comment]
Question, how do we get `fbLSDToken` for ThreadsAPI options?

**Comment by junhoyeo** [comment]
> Question, how do we get `fbLSDToken` for ThreadsAPI options?

Hi, @Digital39999! Currently, this library `threads-api` only supports *reading* data from Threads.

1. **You don't *need* to set `fbLSDToken` manually.** The package includes an default value you can use without zero setup, and updates internal state automatically when it requests to raw doc. **You can just initialize `ThreadsAPI` with empty options:**

```ts
const threadsAPI = new ThreadsAPI()
```

2. If you still *want* to set `fbLSDToken` yourself, you can retrieve it in your own way using the upper code snippet I added to answer @nasty-nick-tv's question, and pass like the following:

```ts
const threadsAPI = new ThreadsAPI({
  fbLSDToken,
  noUpdateLSD: true /* default is `false`, if you want to fix `fbLSDToken` with your provided value, set to `true` */
})`
```

**Comment by Digital39999** [comment]
Ah thank you for information, are there any rate-limits you occurred yet?

**Comment by Digital39999** [comment]
Added custom proxy options in #32 to sort of prevent this from happening.

**Comment by junhoyeo** [comment]
> Also `noUpdateLSD` is in method options, not in class constructor.

Oops, my bad. Should've fixed this.
