### ISSUE TITLE
Device ID not working on return

### ISSUE THREAD

**Issue by heroaltman** [junhoyeo/threads-api#299]
Hey Thanks for the great work Jun 

I think it would increase the API's Usability if there were a way also to get access to the device id that threads-api generates automatically if no deviceId is Provided 

Thanks for this API It is really amazing

**Comment by junhoyeo** [comment]
I think `threadsAPI.deviceID` will work!

https://github.com/junhoyeo/threads-api/blob/9be2fc2d8f2315bfc68bc3f40f7a41879ee376e1/threads-api/src/threads-api.ts#L330
