### ISSUE TITLE
Breaking changes on `getUserIDfromUsername()`

### ISSUE THREAD

**Issue by yssf-io** [junhoyeo/threads-api#31]
Looks like Threads' developers just redirected all Web browser profiles to a login route that redirects back to the homepage.

Try it here: https://www.threads.net/@zuck

PS: other functions still work, but now reverse-engineering will get tougher

**Comment by yssf-io** [comment]
Should be fixed in #33 as it passes the tests.

**Comment by junhoyeo** [comment]
wtf, thanks

**Comment by junhoyeo** [comment]
@yssf-io Your changes have been included in [v1.0.9](https://github.com/junhoyeo/threads-api/releases/tag/v1.0.9)!
