### ISSUE TITLE
Move `noUpdateLSD` in method options to `ThreadsAPI` class constructor

### ISSUE THREAD

**Issue by junhoyeo** [junhoyeo/threads-api#34]
> @Digital39999: Also `noUpdateLSD` is in method options, not in class constructor.

Oops, my bad. Should've fixed this.

_Originally posted by @junhoyeo in https://github.com/junhoyeo/threads-api/issues/26#issuecomment-1626079968_

**Comment by Digital39999** [comment]
Done in #35.

**Comment by junhoyeo** [comment]
@Digital39999 That was fast! Thanks :)

**Comment by Digital39999** [comment]
@junhoyeo Np, glad to help!
