### ISSUE TITLE
Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by torrober** [junhoyeo/threads-api#36]
Hello again, i'm trying to use the api and..
![image](https://github.com/junhoyeo/threads-api/assets/15577163/23da550d-bb18-4aed-891b-57e479e00207)
My code rn:
![image](https://github.com/junhoyeo/threads-api/assets/15577163/620908b7-9d9e-4731-9b17-dc1af21de870)

I've installed the library directly from npm.

**Comment by torrober** [comment]
tried re-installing and nothing happens :/

**Comment by torrober** [comment]
strangely, running via node works. Might refactor this app in node

**Comment by junhoyeo** [comment]
Will see through, btw I don't think calling this package on the browser isn't a great idea (yet).

**Comment by junhoyeo** [comment]
> strangely, running via node works. Might refactor this app in node

- I'll see if I can add browser support, but even so we should still need something to proxy requests
- If you're using Next.js how about using [API Routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes), Server Components, or Route Handlers, .etc.

**Comment by torrober** [comment]
I ended up refactoring my app with node and express, just to make things easier.

**Comment by iamdeepak92** [comment]
This is the first Threads scraper code. This requires no login . I think this will help someone.

https://github.com/iamdeepak92/threads-scraper
