### ISSUE TITLE
TypeError: threads_api__WEBPACK_IMPORTED_MODULE_3__.ThreadsAPI.getUserIDfromUsername is not a function

### ISSUE THREAD

**Issue by mintway0341** [junhoyeo/threads-api#38]
I am using the api in React.
```js
const onBtnClickHandler = async () => {
  const threadsAPI = new ThreadsAPI();
  console.log(threadsAPI);
  const userID = await ThreadsAPI.getUserIDfromUsername(username);
  if (!userID) {
    alert("유저 정보가 없습니다.");
    return;
  }
  const user = await threadsAPI.getUserProfile(username, userID);
  console.log(JSON.stringify(user));
};
```

Why does this error occur?
<img width="811" alt="스크린샷 2023-07-08 오전 11 12 37" src="https://github.com/junhoyeo/threads-api/assets/44641348/119a67ac-2e61-4738-b90a-d743d5ffad67">

**Comment by junhoyeo** [comment]
Will see through, btw I don't think calling this package on the browser isn't a great idea (yet).

**Comment by Manfies** [comment]
Yes, same here. But I can see that you are using client side request on Next. I just moved the logic into getServerSideProps and it works as expected.

**Comment by mintway0341** [comment]
There was a typo. I changed ThreadsAPI to threadsAPI.
