### ISSUE TITLE
forbidden when access image candidates url from threads

### ISSUE THREAD

**Issue by gadingnst** [junhoyeo/threads-api#41]
maybe it's not an issue. but currently, I can't load any image candidates url, do you have any suggestions to solve this?

![Screenshot 2023-07-08 at 13 28 38](https://github.com/junhoyeo/threads-api/assets/38345393/d35c9fea-562b-4cf9-b6ee-5abca276ab0f)

BTW, thanks for the API! 🔥

**Comment by junhoyeo** [comment]
Hi, @gadingnst! Nice to see you experimenting. 👍 
You need to proxy requests using a separate server. If you're using Next.js >= 12.3, you can use [`<Image />` and the config `images. remotePatterns`](https://nextjs.org/docs/pages/api-reference/components/image#remotepatterns) like the following:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.cdninstagram.com',
      },
      {
        protocol: 'https',
        hostname: '**.fbcdn.net',
      },
    ],
  },
};

module.exports = nextConfig;
```

If not, you should use/implement something like [Blazity/next-image-proxy](https://github.com/Blazity/next-image-proxy).

**Comment by gadingnst** [comment]
solved. thanks, mate.
