### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Colin-Moran** [junhoyeo/threads-api#54]
`import pkg from 'threads-api';
const { ThreadsAPI } = pkg;

const main = async () => {
  const threadsAPI = new ThreadsAPI({
    username: 'username', // Your username
    password: 'password', // Your password
  });

  await threadsAPI.publish('🤖 Hello World');
};

main();`

When attempting to use the publish function I receive this error: 

Cannot read properties of undefined (reading 'split')
    at i.<anonymous> (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:7479)
    at C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:1700
    at Object.next (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:1805)
    at t (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:281)
    at i (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:478)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Does anyone know a solution?

**Comment by iamdeepak92** [comment]
This is the first Threads scraper code. This requires no login . I think this will help someone.

https://github.com/iamdeepak92/threads-scraper

**Comment by Mineru98** [comment]
> This is the first Threads scraper code. This requires no login . I think this will help someone.
> 
> https://github.com/iamdeepak92/threads-scraper

When you want to publish a post, The code in [that link](https://github.com/iamdeepak92/threads-scraper) does not provide functionality.

**Comment by Mineru98** [comment]
> `import pkg from 'threads-api'; const { ThreadsAPI } = pkg;
> 
> const main = async () => { const threadsAPI = new ThreadsAPI({ username: 'username', // Your username password: 'password', // Your password });
> 
> await threadsAPI.publish('🤖 Hello World'); };
> 
> main();`
> 
> When attempting to use the publish function I receive this error:
> 
> Cannot read properties of undefined (reading 'split') at i. (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:7479) at C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:1700 at Object.next (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:1805) at t (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:281) at i (C:\Users\Colin\Documents\GitHub\threads-bot\node_modules\threads-api\build\threads-api.js:1:478) at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> Does anyone know a solution?

Did you change 'username' and 'password'?

1. If I had to guess, neither your Instagram nor your Threads account should be private.
2. It also doesn't work if you have Instagram's secondary security enabled.
3. Check the status of your account's security measures on Instagram.

**Comment by junhoyeo** [comment]
@Colin-Moran Will start taking a look, sorry I was busy today. Thanks for filing an issue!

**Comment by junhoyeo** [comment]
@iamdeepak92 Nice work! Glad to see you building.

**Comment by junhoyeo** [comment]
@iamdeepak92 Nice work! Glad to see you building, but please don't spam to all unrelated issues. 🙏

**Comment by Colin-Moran** [comment]
@Mineru98 @junhoyeo 

I feel silly. I had changed the username and password but after double checking everything I realized I was using an incorrect password for the account I was trying to log in to. 

After resolving that, everything is working as expected! Thanks to both of you for the helpful responses.
