### ISSUE TITLE
How to Post Long Threads Like One after another linked together

### ISSUE THREAD

**Issue by heyishaansinghal** [junhoyeo/threads-api#55]
I can't seem to figure out how to Post Threads that are linked together like Thread on Twitter 

Also, I tried Posting a 500 Character but instead got this error :     data: { message: 'Provided text too long', status: 'fail' }

Steps to Reproduce just paste a long-form tweet in place of Content we can't place it 

And Junhoyeo you really doing a great work 👍️

**Comment by junhoyeo** [comment]
Thanks, I'll add another feature for this.
