### ISSUE TITLE
Get user's timeline?

### ISSUE THREAD

**Issue by threaderzero** [junhoyeo/threads-api#56]
Sorry if I misunderstand the API but is there a way to see the "timeline" of a logged-in user, meaning the page that comes up when you open the app and press press the home icon?

<img width="36" alt="image" src="https://github.com/junhoyeo/threads-api/assets/139019903/81b7d724-d674-4e17-b9ee-96e866342e11">

I am referring to this:

<img width="395" alt="image" src="https://github.com/junhoyeo/threads-api/assets/139019903/cda93590-b8d9-458c-ada7-fd8b140100ed">

**Comment by junhoyeo** [comment]
We don't have this API yet!

**Comment by junhoyeo** [comment]
@threaderzero We now have this in v1.4.2!
