### ISSUE TITLE
Image uploading via `threadsAPI.uploadImage` not working

### ISSUE THREAD

**Issue by junhoyeo** [junhoyeo/threads-api#70]
## Background
`threadsAPI.uploadImage` method added by @Mineru98 (I accidentally merged #62 to main before adding changes, so I made another following PR in #66) isn't working.

**Comment by junhoyeo** [comment]
Oops I was sending the request with wrong URL after refactoring. Sorry @Mineru98 🤣

**Comment by junhoyeo** [comment]
I'll fix this asap

**Comment by junhoyeo** [comment]
my mistake, working on it

**Comment by FieryFlames** [comment]
Maybe publishWithImage should be combined with publish and support multiple images in the same thread.

**Comment by junhoyeo** [comment]
> Maybe publishWithImage should be combined with publish and support multiple images in the same thread.

@FieryFlames super agreed, will do + also we can add auto splitting text requested in #55

**Comment by Mineru98** [comment]
> Maybe publishWithImage should be combined with publish and support multiple images in the same thread.

For now, we only support a single image and will update after we do the relevant rebasing.

**Comment by FieryFlames** [comment]
I started looking into it and from a very initial glance they upload the images but then there's a different request used to add/set the images?

**Comment by Mineru98** [comment]
I'm not sure about that.

**Comment by FieryFlames** [comment]
This is what I'm seeing: 
<img width="761" alt="Screenshot 2023-07-09 at 8 30 54 PM" src="https://github.com/junhoyeo/threads-api/assets/30497388/d31b40e5-caca-4324-a417-feff97ae5a2d">

**Comment by junhoyeo** [comment]
> my mistake, working on it

Problem was with Axios. Done.

**Comment by junhoyeo** [comment]
> Instead of `configure_text_post_app_feed`, they use `configure_text_post_app_sidecar`

Awesome discovery! Thank you a lot :)
