### ISSUE TITLE
Fetch posts with credentials

### ISSUE THREAD

**Issue by Digital39999** [junhoyeo/threads-api#71]
Is this currently possible? I've tried looking in options couldn't find anything promising, this redirect thing they implemented is annoying.

**Comment by Mineru98** [comment]
We haven't explored that feature yet.

**Comment by Digital39999** [comment]
Would probably be good idea to help out on.

**Comment by junhoyeo** [comment]
`getThreadsLoggedIn` was introduced in https://github.com/junhoyeo/threads-api/releases/tag/v1.6.2. Thanks!

**Comment by Digital39999** [comment]
> `getThreadsLoggedIn` was introduced in https://github.com/junhoyeo/threads-api/releases/tag/v1.6.2. Thanks!

Why does it require user Id and not username?
