### ISSUE TITLE
[New Feature Request] Upload multi threads or upload post as reply

### ISSUE THREAD

**Issue by dennis2311** [junhoyeo/threads-api#77]
I'm happy to be able to post automatically on Threads. I really appreciate your work.

However, there's one more function I want, that uploading in multi-threads form from the beginning.
(You can type enter three times when you upload a post in the threads app or press the 'Add to Thread' text.)

Of course, it doesn't work just by putting line-break in the parameter of the .publish() function more than three times.

I tried myself to find out if the API is different, but my reverse-engineering skills are still immature, so I haven't figured it out yet.

Is it possible to add that function? I saw that 'Reply to existing Thread' is in the roadmap you set, but personally, I would be happy if it is advanced.

Thank you.

**Comment by junhoyeo** [comment]
@dennis2311 I was just about to open a PR for this! 👍

**Comment by junhoyeo** [comment]
- Gonna deploy #78 now. Added replying & link support
- I'll keep track of the multi-threads feature in #55
