### ISSUE TITLE
Support publishing with multiple images

### ISSUE THREAD

**Issue by FieryFlames** [junhoyeo/threads-api#82]
Maybe publishWithImage should be combined with publish and support multiple images in the same thread.

_Originally posted by @FieryFlames in https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627872326_
           
              This is what I'm seeing:
<img width="761" alt="Screenshot 2023-07-09 at 8 30 54 PM" src="https://github.com/junhoyeo/threads-api/assets/30497388/d31b40e5-caca-4324-a417-feff97ae5a2d">

Instead of `configure_text_post_app_feed`, they use `configure_text_post_app_sidecar`

_Originally posted by @FieryFlames in https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627881723_

**Comment by junhoyeo** [comment]
superr thank you so much for the reversing work!

**Comment by junhoyeo** [comment]
Hi @FieryFlames, we now support sidecar attachments from [v1.5.0](https://github.com/junhoyeo/threads-api/releases/tag/v1.5.0) (#198)! 🎉

**Comment by MsLolita** [comment]
> ```
>           Maybe publishWithImage should be combined with publish and support multiple images in the same thread.
> ```
> 
> _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627872326)_
> 
> ```
>           This is what I'm seeing:
> ```
> 
> <img alt="Screenshot 2023-07-09 at 8 30 54 PM" width="761" src="https://user-images.githubusercontent.com/30497388/252180777-d31b40e5-caca-4324-a417-feff97ae5a2d.png">
> Instead of `configure_text_post_app_feed`, they use `configure_text_post_app_sidecar`
> 
> _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627881723)_



> ```
>           Maybe publishWithImage should be combined with publish and support multiple images in the same thread.
> ```
> 
> _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627872326)_
> 
> ```
>           This is what I'm seeing:
> ```
> 
> <img alt="Screenshot 2023-07-09 at 8 30 54 PM" width="761" src="https://user-images.githubusercontent.com/30497388/252180777-d31b40e5-caca-4324-a417-feff97ae5a2d.png">
> Instead of `configure_text_post_app_feed`, they use `configure_text_post_app_sidecar`
> 
> _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627881723)_

Hello @FieryFlames , can you tell me how you managed to sniff the traffic?

**Comment by FieryFlames** [comment]
> > ```
> 
> >           Maybe publishWithImage should be combined with publish and support multiple images in the same thread.
> 
> > ```
> 
> > 
> 
> > _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627872326)_
> 
> > 
> 
> > ```
> 
> >           This is what I'm seeing:
> 
> > ```
> 
> > 
> 
> > <img alt="Screenshot 2023-07-09 at 8 30 54 PM" width="761" src="https://user-images.githubusercontent.com/30497388/252180777-d31b40e5-caca-4324-a417-feff97ae5a2d.png">
> 
> > Instead of `configure_text_post_app_feed`, they use `configure_text_post_app_sidecar`
> 
> > 
> 
> > _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627881723)_
> 
> 
> 
> 
> 
> 
> 
> > ```
> 
> >           Maybe publishWithImage should be combined with publish and support multiple images in the same thread.
> 
> > ```
> 
> > 
> 
> > _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627872326)_
> 
> > 
> 
> > ```
> 
> >           This is what I'm seeing:
> 
> > ```
> 
> > 
> 
> > <img alt="Screenshot 2023-07-09 at 8 30 54 PM" width="761" src="https://user-images.githubusercontent.com/30497388/252180777-d31b40e5-caca-4324-a417-feff97ae5a2d.png">
> 
> > Instead of `configure_text_post_app_feed`, they use `configure_text_post_app_sidecar`
> 
> > 
> 
> > _Originally posted by @FieryFlames in [#70 (comment)](https://github.com/junhoyeo/threads-api/issues/70#issuecomment-1627881723)_
> 
> 
> 
> Hello @FieryFlames , can you tell me how you managed to sniff the traffic?

https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/tree/9b15af2d984a2e39f8c677864c4b2bb7626f30b4 and mitmproxy
