### ISSUE TITLE
Support for pagination for Threads and Replies

### ISSUE THREAD

**Issue by chbrown1293** [junhoyeo/threads-api#90]
Curious if there is a plan to support pagination in retrieving threads and replies? Seems limited too 25 right now, unless im missing something. Great work BTW!

**Comment by wack-overflow** [comment]
I noticed (for likers) that even the mobile app doesn't show more than 100, though it definately does pagination for replies so hopefully it's possible 🤞

**Comment by junhoyeo** [comment]
Deployed in v1.4.2 (Related - #157, #150, #153)
