### ISSUE TITLE
Cannot run API on server

### ISSUE THREAD

**Issue by a-burlakovv** [junhoyeo/threads-api#96]
Problem with the 'build' script: When trying to run npm run build or yarn build in the threads-api directory, the script is not recognized or found. This is despite the fact that the build script is mentioned in the project's documentation.

Cannot find module 'threads-api': When trying to build the threads-web-ui project, the build process fails with an error stating that it cannot find the 'threads-api' module. This error occurs even after attempting to install the 'threads-api' module using both npm and yarn.

Issues with 'next' version: The react-threads package seems to require a specific version of 'next' that is not being satisfied. Attempts to upgrade 'next' to the required version have not resolved this issue.

Problems with the 'start' script: Similar to the 'build' script issue, running npm start or yarn start in the threads-api directory results in an error stating that the script cannot be found.

Issues with 'yarn add ../threads-api': When trying to add the 'threads-api' module to the threads-web-ui project using yarn add ../threads-api, the build process still fails with the same error stating that it cannot find the 'threads-api' module.

These issues have prevented the successful setup and running of the project as described in the documentation. Any assistance or guidance on how to resolve these issues would be greatly appreciated.

![image](https://github.com/junhoyeo/threads-api/assets/130252452/863d849f-b55f-40aa-b63a-eb52f837f10c)

**Comment by yssf-io** [comment]
For the `build` and `start` commands, make sure you're in the threads-api subfolder (`threads-api/threads-api`).

For the web-ui, it's because you need to `yarn build` the `threads-api` package.

**Comment by a-burlakovv** [comment]
it worked! thank you
